# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(782, 464)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 20, 631, 161))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(60, 150, 681, 151))
        self.label_2.setObjectName("label_2")
        self.promise_input = QtWidgets.QLineEdit(Dialog)
        self.promise_input.setGeometry(QtCore.QRect(60, 350, 521, 20))
        self.promise_input.setObjectName("promise_input")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(60, 310, 631, 16))
        self.label_3.setObjectName("label_3")
        self.button_ok = QtWidgets.QPushButton(Dialog)
        self.button_ok.setGeometry(QtCore.QRect(560, 410, 75, 23))
        self.button_ok.setObjectName("button_ok")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Reminder"))
        self.label.setText(_translate("Dialog", "同学们：\n"
"很高兴我制作的程序给你们带来了便利。但是，我现在想和你们谈谈关于学习的事情。  \n"
"我们都知道，学习是为自己学的，而不是为了父母，老师，更不是为了欺骗ewt的那点数据。  \n"
"此程序只是为了让那些觉得e网通课程真的没什么用的同学不用浪费时间，读书为自己，请不要滥用此程序！  \n"
"建议课程视频先挑着看对自己有用的，再用本脚本！ "))
        self.label_2.setText(_translate("Dialog", "Dear Classmates:\n"
"I am glad that the program I created has brought you convenience. But now I want to talk to you about learning.\n"
"We all know that learning is for oneself, not for parents, teachers, or to deceive EWT\'s data.\n"
"This program is just for those students who feel that the EWT course is really useless to avoid wasting time.\n"
"Please do not abuse this program!\n"
"Suggest selecting the course videos that are useful to you before using this script!"))
        self.label_3.setText(_translate("Dialog", "请在下面的横线中填写：“我保证会好好学习，合理利用此工具，并已知悉此工具可能存在的未知风险”"))
        self.button_ok.setText(_translate("Dialog", "OK"))
